version: "3.9"

services:
  web:
    image: celnet1/reactapp-frontend:v1.0
    ports:
      - "3000:3000"
    restart: always

  api:
    image: celnet1/python-docker:latest
    ports:
      - "8000:8000"
    restart: always
